version: 0.1

phases:
    install:
        commands:
            - echo INSTALL started on `date`
            - npm install gulp -g
            - npm install
    build:
        commands:
            - echo Building bundles started on `date`
            - gulp default
    post_build:
        commands:
            - echo Build completed on `date`
artifacts:
    files:
        - '**/*'
    base-directory: dist
