version: 0.1

phases:
    install:
        commands:
            - npm install
    build:
        commands:
            - echo Building bundles
            - gulp default
    post_build:
        commands:
            - echo Build completed on `date`
artifacts:
    files:
        - dist/**/*
